define(function(require){
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/input/input');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/tabs/tabs');
require('$model/UI2/system/components/bootstrap/row/row');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/select/checkboxGroup');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/dataTables/dataTables');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/button/checkbox');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/window/window');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/demo/pcSample/form-element/filterConditionEight'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='';
	this.__cid='cqMvaYr';
	this._flag_='925db67aadb31b215e327518872bdc13';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"},"flow":{"define":"flow","label":"资金流向","name":"flow","relation":"flow","type":"String"}},"directDelete":false,"events":{},"idColumn":"fID","initData":"[{\"flow\":\"全部\"},{\"flow\":\"收入\"},{\"flow\":\"支出\"},{\"flow\":\"转入\"},{\"flow\":\"转出\"}]","limit":20,"xid":"flowData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":false,"confirmRefresh":true,"defCols":{"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"},"flow":{"define":"flow","label":"资金流向","name":"flow","relation":"flow","type":"String"}},"directDelete":false,"events":{"onValueChanged":"flowDefaultValueChanged"},"idColumn":"fID","initData":"[{}]","limit":20,"xid":"flowDefault"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":false,"confirmRefresh":true,"defCols":{"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"},"flow":{"define":"flow","label":"资金流向","name":"flow","relation":"flow","type":"String"}},"directDelete":false,"events":{},"idColumn":"fID","limit":20,"xid":"flowFilter"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"account":{"define":"account","label":"账户类型","name":"account","relation":"account","type":"String"},"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"}},"directDelete":false,"events":{},"idColumn":"fID","initData":"[{\"account\":\"个人账户\"},{\"account\":\"公司账户\"}]","limit":20,"xid":"accountData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":false,"confirmRefresh":true,"defCols":{"account":{"define":"account","label":"账户","name":"account","relation":"account","type":"String"},"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"}},"directDelete":false,"events":{"onValueChanged":"accountDefaultValueChanged"},"idColumn":"fID","initData":"[{}]","limit":20,"xid":"accountDefault"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":false,"confirmRefresh":true,"defCols":{"account":{"define":"account","label":"账户","name":"account","relation":"account","type":"String"},"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"}},"directDelete":false,"events":{},"idColumn":"fID","limit":20,"xid":"accountFilter"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"},"type":{"define":"type","label":"类型","name":"type","relation":"type","type":"String"}},"directDelete":false,"events":{},"idColumn":"fID","initData":"[{\"type\":\"全部\"},{\"type\":\"衣服饰品\"},{\"type\":\"食品酒水\"},{\"type\":\"居家物业\"},{\"type\":\"行车交通\"},{\"type\":\"交流通讯\"},{\"type\":\"玩乐休闲\"},{\"type\":\"学习培训\"},{\"type\":\"礼金慈善\"},{\"type\":\"医疗保健\"},{\"type\":\"生儿育女\"},{\"type\":\"偶然支出\"},{\"type\":\"差旅公务\"},{\"type\":\"企业支出\"},{\"type\":\"杂项支出\"},{\"type\":\"网上购物\"},{\"type\":\"职业工薪\"},{\"type\":\"业余工薪\"},{\"type\":\"人情收入\"},{\"type\":\"偶然收入\"},{\"type\":\"公务收入\"},{\"type\":\"企业收入\"},{\"type\":\"杂项收入\"}]","limit":20,"xid":"typeData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"},"type":{"define":"type","label":"类型","name":"type","relation":"type","type":"String"}},"directDelete":false,"events":{"onValueChanged":"typeDefaultValueChanged"},"idColumn":"fID","initData":"[{\"fID\":\"\",\"type\":\"\"}]","limit":20,"xid":"typeDefault"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":false,"confirmRefresh":true,"defCols":{"fID":{"define":"fID","label":"ID","name":"fID","relation":"fID","type":"String"},"type":{"define":"type","label":"类型","name":"type","relation":"type","type":"String"}},"directDelete":false,"events":{},"idColumn":"fID","limit":20,"xid":"tyeFilter"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"date":{"define":"date","label":"时间","name":"date","relation":"date","type":"String"}},"directDelete":false,"events":{},"idColumn":"date","limit":20,"xid":"date"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"keyword":{"define":"keyword","label":"关键词","name":"keyword","relation":"keyword","type":"String"}},"directDelete":false,"events":{},"idColumn":"keyword","limit":20,"xid":"keyData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"tAge":{"define":"tAge","label":"年龄 ","name":"tAge","relation":"tAge","rules":{"integer":true},"type":"Integer"},"tID":{"define":"tID","label":"ID","name":"tID","relation":"tID","type":"String"},"tName":{"define":"tName","label":"姓名","name":"tName","relation":"tName","type":"String"},"tSex":{"define":"tSex","label":"性别","name":"tSex","relation":"tSex","type":"String"}},"directDelete":false,"events":{},"idColumn":"tID","initData":"[{\"tID\":\"1\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":21},{\"tID\":\"2\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":22},{\"tID\":\"3\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":23},{\"tID\":\"4\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":24},{\"tID\":\"5\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":25},{\"tID\":\"6\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":26},{\"tID\":\"7\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":27},{\"tID\":\"8\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":28},{\"tID\":\"9\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":29},{\"tID\":\"10\",\"tName\":\"张小三\",\"tSex\":\"男\",\"tAge\":20}]","limit":20,"xid":"data"});
}}); 
return __result;});