import java.util.HashMap;

import com.justep.system.data.DatabaseProduct;
import com.justep.system.data.Table;
import com.justep.system.data.SQL;


public class ChartProcedure {

	/**
	 * 饼图
	 * @return
	 */
	public static Table pieQuery(){
		String oracle = "SELECT RCATEGORYNAME ,SUM(RPRICE) AS RSUMPRICE FROM ( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME ,RUNITPRICE*RUNITSINSTOCK AS RPRICE FROM DEMO_REPORTPRODUCTS)A GROUP BY A.RCATEGORYNAME";
		String mssql = "SELECT RCATEGORYNAME ,SUM(RPRICE) AS RSUMPRICE FROM ( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME ,RUNITPRICE*RUNITSINSTOCK AS RPRICE FROM DEMO_REPORTPRODUCTS)A GROUP BY A.RCATEGORYNAME";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	/**
	 * 垂直柱图
	 * @return
	 */
	public static Table barVQuery(){
		
		String oracle = "SELECT RCOMPANYNAME , RCATEGORYNAME ,SUM(CB) AS RCB FROM( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID IN ('1','2','3','4'))A GROUP BY A.RCOMPANYNAME ,A.RCATEGORYNAME";
		String mssql = "SELECT RCOMPANYNAME , RCATEGORYNAME ,SUM(CB) AS RCB FROM( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID = '1' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '2' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '3' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '4')A GROUP BY A.RCOMPANYNAME ,A.RCATEGORYNAME";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	/**
	 * 水平柱图
	 * @return
	 */
	public static Table barHQuery(){
		
		String oracle = "SELECT RCOMPANYNAME , RCATEGORYNAME ,SUM(CB) AS RCB FROM( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID IN ('1','2','3','4'))A GROUP BY A.RCOMPANYNAME ,A.RCATEGORYNAME";
		String mssql = "SELECT RCOMPANYNAME , RCATEGORYNAME ,SUM(CB) AS RCB FROM( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID = '1' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '2' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '3' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '4')A GROUP BY A.RCOMPANYNAME ,A.RCATEGORYNAME";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		
		return SQL.select(sqlMap,null,"/demo/report/data");
	}
	
	/**
	 * 线图
	 * @return
	 */
	public static Table lineQuery1(){
		
		String oracle = "SELECT RORDERYEAR, RORDERMONTH , SUM(SUM_PRICE) AS RSUMPRICE FROM ( SELECT RORDERID, to_char(RORDERDATE, 'yyyy ')AS RORDERYEAR , to_char(RORDERDATE,'mm') AS RORDERMONTH , ( SELECT B.SUM_PRICE FROM (SELECT RORDERID , SUM(RUNITPRICE*RQUANTITY*RDISCOUNT) AS SUM_PRICE FROM DEMO_REPORTORDERDETAILS GROUP BY RORDERID) B WHERE B.RORDERID = DEMO_REPORTORDERS.RORDERID ) AS SUM_PRICE FROM DEMO_REPORTORDERS )C GROUP BY RORDERYEAR ,RORDERMONTH order by RORDERYEAR,rordermonth";
		String mssql = "SELECT RORDERYEAR, RORDERMONTH , SUM(SUM_PRICE) AS RSUMPRICE FROM ( SELECT RORDERID, YEAR(RORDERDATE)AS RORDERYEAR , MONTH(RORDERDATE) AS RORDERMONTH , ( SELECT B.SUM_PRICE FROM (SELECT RORDERID , SUM(RUNITPRICE*RQUANTITY*RDISCOUNT) AS SUM_PRICE FROM DEMO_REPORTORDERDETAILS GROUP BY RORDERID) B WHERE B.RORDERID = DEMO_REPORTORDERS.RORDERID ) AS SUM_PRICE FROM DEMO_REPORTORDERS )C GROUP BY RORDERYEAR ,RORDERMONTH";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	public static Table lineQuery2(){
		
		String oracle = "SELECT RLOTTERYID, RSTAGE, RLOTTERYNUM1, RLOTTERYNUM2, RLOTTERYNUM3 FROM DEMO_REPORTCHARTLOTTERY";
		String mssql = "SELECT RLOTTERYID, RSTAGE, RLOTTERYNUM1, RLOTTERYNUM2, RLOTTERYNUM3 FROM DEMO_REPORTCHARTLOTTERY";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	/**
	 * 面积图
	 * @return
	 */
	public static Table areaQuery(){
		
		String oracle = "SELECT RCOMPANYNAME , RCATEGORYNAME ,SUM(CB) AS CB FROM ( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID IN ('1','2','3','4'))A GROUP BY A.RCOMPANYNAME ,A.RCATEGORYNAME";
		String mssql = "SELECT RCOMPANYNAME , RCATEGORYNAME ,SUM(CB) AS CB FROM ( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID = '1' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '2' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '3' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '4')A GROUP BY A.RCOMPANYNAME ,A.RCATEGORYNAME";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	/**
	 * 甘特图
	 * @return
	 */
	public static Table ganttQuery(){
		
		String oracle = "SELECT RPROJECTROLE ,RPROJECTTYPE , RSTARTTIME ,RENDTIME ,RPLANSTARTTIME ,RPLANENDTIME FROM DEMO_REPORTCHARTPROJECT";
		String mssql = "SELECT RPROJECTROLE ,RPROJECTTYPE , RSTARTTIME ,RENDTIME ,RPLANSTARTTIME ,RPLANENDTIME FROM DEMO_REPORTCHARTPROJECT";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	/**
	 * 累积对比分析
	 * @return
	 */
	public static Table accumulationQuery(){
		
		String oracle = "SELECT A.RCATEGORYNAME ,SUM(A.CB) AS ALL_CB FROM ( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS )A GROUP BY A.RCATEGORYNAME";
		String mssql = "SELECT A.RCATEGORYNAME ,SUM(A.CB) AS ALL_CB FROM ( SELECT (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , RUNITPRICE*RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS )A GROUP BY A.RCATEGORYNAME";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}
}