import java.util.HashMap;

import com.justep.system.data.DatabaseProduct;
import com.justep.system.data.Table;
import com.justep.system.data.SQL;

public class PropertyReportProcedure {

	/**
	 * 报图混合表
	 * @return
	 */
	public static Table chartQuery1(){
		
		String oracle = "SELECT RPRODUCTID , RPRODUCTNAME , (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RQUANTITYPERUNIT,RUNITPRICE,RUNITSINSTOCK FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID IN ('1','2','3','4')";
		String mssql = "SELECT RPRODUCTID , RPRODUCTNAME , (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME, RQUANTITYPERUNIT,RUNITPRICE,RUNITSINSTOCK FROM DEMO_REPORTPRODUCTS WHERE (DEMO_REPORTPRODUCTS.RSUPPLIERID = '1' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '2' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '3' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '4')";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}

	public static Table chartQuery2(){
		
		String oracle = "SELECT COMPANYNAME , CATEGORYNAME ,SUM(CB) AS CB FROM( SELECT ( SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS CATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS COMPANYNAME, RUNITPRICE * RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID IN ('1','2','3','4'))A GROUP BY A.COMPANYNAME ,A.CATEGORYNAME";
		String mssql = "SELECT COMPANYNAME , CATEGORYNAME ,SUM(CB) AS CB FROM( SELECT ( SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS CATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS COMPANYNAME, RUNITPRICE * RUNITSINSTOCK AS CB FROM DEMO_REPORTPRODUCTS WHERE DEMO_REPORTPRODUCTS.RSUPPLIERID = '1' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '2' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '3' OR DEMO_REPORTPRODUCTS.RSUPPLIERID = '4')A GROUP BY A.COMPANYNAME ,A.CATEGORYNAME";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}
	
	/**
	 * 参数查询
	 * @return
	 */
	public static Table parameterFilterQuery(String name, String id){
		
		String oracle = "SELECT RPRODUCTID , RPRODUCTNAME , (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME,RQUANTITYPERUNIT,RUNITPRICE,RUNITSINSTOCK FROM DEMO_REPORTPRODUCTS";
		String mssql = "SELECT RPRODUCTID , RPRODUCTNAME , (SELECT RCATEGORYNAME FROM DEMO_REPORTPRODUCTCATEGORY WHERE DEMO_REPORTPRODUCTCATEGORY.RCATEGORYID = DEMO_REPORTPRODUCTS.RCATEGORYID) AS RCATEGORYNAME , (SELECT RCOMPANYNAME FROM DEMO_REPORTSUPPLIERS WHERE DEMO_REPORTSUPPLIERS.RSUPPLIERID = DEMO_REPORTPRODUCTS.RSUPPLIERID)AS RCOMPANYNAME,RQUANTITYPERUNIT,RUNITPRICE,RUNITSINSTOCK FROM DEMO_REPORTPRODUCTS";
		
		oracle += " WHERE 1=1 ";
		mssql += " WHERE 1=1 ";
		
		if(!"".equals(name)){
			oracle += "and RPRODUCTNAME like '%"+name+"%' ";
			mssql += "and RPRODUCTNAME like '%"+name+"%' ";
		}
		if(!"".equals(id)){
			oracle += String.format("and RPRODUCTID = '%s' ", id);
			mssql += String.format("and RPRODUCTID = '%s' ", id);
		}
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put(SQL.DEFAULT_DB_NAME,mssql);
		sqlMap.put(DatabaseProduct.ORACLE.name(),oracle);
		sqlMap.put(DatabaseProduct.MSSQL.name(),mssql);
		sqlMap.put(DatabaseProduct.KINGBASE.name(),oracle);
		sqlMap.put(DatabaseProduct.SYBASE.name(),mssql);
		sqlMap.put(DatabaseProduct.DB2.name(),oracle);
		return SQL.select(sqlMap,null,"/demo/report/data");
	}
}